[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trazzo-tools"
version = "1.0.1"
description = "CLI for creating, exporting, viewing, and editing Trazzo brush archives (.tzb)"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "EralexFl" }
]
keywords = ["cli", "brush", "trazzo", "tzb"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Environment :: Console",
]
dependencies = ["click", "peewee", "python-dotenv", "rich", "build"]
optional-dependencies.dev = ["pytest"]

[project.scripts]
trazzo-tools = "trazzo_tools.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
